### ISSUE TITLE
Memory release will raise error should CPU fail to detect

### ISSUE THREAD

**Issue by JamiePoco** [Excel-lent/ClooWrapperVBA#4]
![image](https://github.com/Excel-lent/ClooWrapperVBA/assets/141510146/2b65c2df-0b6a-4a7b-b857-ea5fc1555933)

The above error is raised @ result = programDevice_Performance.ReleaseMemObject(1) in  GpuCpu_SingleDouble_PerformanceTest

I am running Xeon processor and  GetFirstDeviceOfType(progDevices, "GPU") returns Nothing
The result of that is "Set programDevice_Performance = GetFirstDeviceOfType(progDevices, "GPU")" does not get ran however "result = programDevice_Performance.ReleaseMemObject(1)" does still run which results in the error

Simple fix, move the clean-up code in to the Else statement so it only runs should it be created.

Better still add support for Xeon processors.

Great project by the way, just spent all day porting it to VB6, interestingly the VBA performance test is much slower in Excel than in VB6 

![image](https://github.com/Excel-lent/ClooWrapperVBA/assets/141510146/bdefb51d-4a8f-497e-a9af-92dc8397d7b4)

**Comment by Excel-lent** [comment]
Thank you for bringing the issue to my attention! I have fixed the error and believe that the issue is now resolved.
Regarding Xeon processors, it is recommended that you install the latest drivers, as detailed in the article "[OpenCL™ Drivers and Runtimes for Intel® Architecture](https://www.codeproject.com/Articles/1230011/OpenCL-Drivers-and-Runtimes-for-Intel-Architectu)". This is because neither ClooWrapperVba, Cloo, nor OpenCL Dll are responsible for the recognition of the device and compilation of OpenCL code; rather, it is the device drivers that handle these tasks.
Additionally, you may find it helpful to read the discussion in "[How to Use Your GPU in .NET](https://www.codeproject.com/Articles/1116907/How-to-Use-Your-GPU-in-NET)", as Xeon processors are also mentioned there.
I am delighted that my simple yet powerful project has piqued your interest. It is surprising that despite OpenCL’s existence since 2009, no one has written a library to support it.
Please note that performance in VBA may be lower than in VB6 due to the trade-off for more powerful debugging capabilities. In VBA, it is possible to change the code during a debugging session and have it executed without recompiling the sources.
I hope this information is helpful! Let me know if you have any further questions or concerns. 

I have updated the files also at [SourceForge](https://sourceforge.net/projects/cloowrappervba/).
